name: CI/CD pipeline for Go microservice to K8s

on:
  push:
    branches:
      - main

  jobs:
    deployment:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up .env file
          run: |
            cp .env.example .env
            sed -i "s|API_KEY=|API_KEY=${{ secrets.API_KEY }}|" .env

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/sentence-analyzer:latest

        - name: Setup Terraform
          working-directory: terraform
          uses: hashicorp/setup-terraform@v3

        - name: Initiate Terraform
          working-directory: terraform
          run: terraform init

        - name: Validate Terraform
          working-directory: terraform
          run: terraform validate

        - name: Plan Terraform
          working-directory: terraform
          run: terraform plan

        - name: Apply Terraform
          working-directory: terraform
          run: terraform apply -auto-approve

        - name: Get EC2 IP from Terraform
          id: tf_output
          working-directory: terraform
          run: |
            echo "server_ip=$(terraform output -raw server_ip)" >> $GITHUB_ENV

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Ansible
          run: pip install "ansible>=9,<10"

        - name: Write SSH private key (ansible/ssh_key)
          working-directory: ansible
          run: |
            cat > ssh_key <<'EOF' ${{ secrets.SSH_PRIVATE_KEY }} EOF chmod 600 ssh_key

        - name: Insert server IP into hosts.ini
          working-directory: ansible
          run: sed -i "s|__SERVER_IP__|${{ env.server_ip }}|g" hosts.ini

        - name: Run Ansible playbook
          working-directory: ansible
          run: ansible-playbook -i hosts.ini configuration.yml -v
